services:
  ute2mqtt:
    build: .
    container_name: ute2mqtt
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Montevideo
    volumes:
      - ./credentials:/app/credentials
    networks:
      - default

  ute-history:
    build: .
    command: ["python", "history_main.py"]
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=America/Montevideo
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
    networks:
      - default

networks:
  default:
    name: ute2mqtt-network
